version: '3.5'

#
# WARNING: ${xxx:?ttt} does not work on some docker-compose version
#

services:
  storagenode:
    image: storjlabs/storagenode:latest
    container_name: storagenode1
    restart: unless-stopped
    volumes:
       - ${IDENTITY_DIR:-./identity_dir/}:/app/identity/:ro
       - ${STORAGE_DIR:-./storage_dir/config/}:/app/config/
    ports:
       - "14002:14002"
    environment:
       - WALLET=${WALLET}
       - EMAIL=${EMAIL}
       - ADDRESS=${NODE_PUBLIC_ADDRESS}:${NODE_PUBLIC_TCP_PORT:-28967}
       - STORAGE=${STORAGE:-1TB}
       - SETUP=${SETUP:-"false"}
    command:
       - --log.level=${LOG_LEVEL:-info}

  tcp-forward2storagenode:
    image: alpine/socat
    restart: unless-stopped
    ports:
      - "${NODE_PUBLIC_TCP_PORT:-28967}:28967/tcp"
    command: -d TCP-LISTEN:28967,fork,reuseaddr TCP-CONNECT:storagenode:28967

  udp-forward2storagenode:
    image: alpine/socat
    restart: unless-stopped
    ports:
      - "${NODE_PUBLIC_UDP_PORT:-28967}:28967/udp"
    command: -d UDP-LISTEN:28967,fork,reuseaddr UDP-SENDTO:storagenode:28967

  watchtover:
    image: containrrr/watchtower
    container_name: watchtower4storjnode1
    restart: unless-stopped
    env_file:
       - ./watchover.env
    command: storagenode1 watchtower4storjnode1
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  prometheus-exporter:
    image: anclrii/storj-exporter:latest
    restart: unless-stopped
    ports:
       - "9651:9651"
    environment:
       - STORJ_HOST_ADDRESS=storagenode1
