version: '3.5'

services:
  storagenode:
    image: storjlabs/storagenode:latest
    container_name: storagenode1
    restart: unless-stopped
    volumes:
       - ${IDENTITY_DIR:?adjust .env}:/app/identity/:ro
       - ${STORAGE_DIR:-./storage_dir/config/}:/app/config/
    ports:
       - "14002:14002"
    environment:
       - WALLET=${WALLET}
       - EMAIL=${EMAIL}
       - ADDRESS=${NODE_PUBLIC_ADDRESS}:${NODE_PUBLIC_TCP_PORT:-28967}
       - STORAGE=${STORAGE:-1TB}
    command:
       - --log.level=${LOG_LEVEL:-info}

  tcp-forward2storagenode:
    image: alpine/socat
    restart: unless-stopped
    ports:
      - "${NODE_PUBLIC_TCP_PORT}:28967/tcp"
    command: -d TCP-LISTEN:28967,fork,reuseaddr TCP-CONNECT:storagenode:28967

  udp-forward2storagenode:
    image: alpine/socat
    restart: unless-stopped
    ports:
      - "${NODE_PUBLIC_TCP_PORT}:28967/udp"
    command: -d UDP-LISTEN:28967,fork,reuseaddr UDP-SENDTO:storagenode:28967

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: storagenode1 watchtower --stop-timeout 300s
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock